spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mental_health_platform
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  h2:
    console:
      enabled: false

logging:
  level:
    com.mantra: INFO
    org.springframework.security: WARN